server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:p6spy:mysql://localhost:3306/ssmdemo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

#mybatis plus 设置
mybatis-plus: 
  mapper-locations: classpath*:mappers/*/*Mapper.xml
  type-aliases-package: com.yicj.study.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
 
logging:
  level:
    root: info
    com.yicj.study.user.mapper: debug
  pattern:
    console: '%p%m%n' 