server:
  port: 8080 #修改默认端口号，默认为8080
  servlet:
    context-path: / #修改默认contextPath,默认为/

spring:
  thymeleaf:
    cache: false #开发过程中建议关闭cache
#    encoding: UTF-8 #thymeleaf编码
#    suffix: .html #thymeleaf后缀
#    servlet:
#      content-type: text/html; charset=utf-8
  freemarker:
    cache: false
#    charset: UTF-8
#    suffix: .ftl
#    content-type: text/html; charset=utf-8
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
   
